#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-virtus
Version  : 1.0.5
Release  : 4
URL      : https://rubygems.org/downloads/virtus-1.0.5.gem
Source0  : https://rubygems.org/downloads/virtus-1.0.5.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
[gem]: https://rubygems.org/gems/virtus
[travis]: https://travis-ci.org/solnic/virtus
[gemnasium]: https://gemnasium.com/solnic/virtus
[codeclimate]: https://codeclimate.com/github/solnic/virtus
[coveralls]: https://coveralls.io/r/solnic/virtus
[inchpages]: http://inch-ci.org/github/solnic/virtus/

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n virtus-1.0.5
gem spec %{SOURCE0} -l --ruby > rubygem-virtus.gemspec

%build
gem build rubygem-virtus.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
virtus-1.0.5.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/virtus-1.0.5.gem
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/.pelusa.yml
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/.rspec
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/.ruby-gemset
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/.ruby-version
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/Changelog.md
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/Guardfile
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/README.md
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/TODO.md
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/attribute.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/attribute/accessor.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/attribute/boolean.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/attribute/builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/attribute/coercer.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/attribute/coercible.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/attribute/collection.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/attribute/default_value.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/attribute/default_value/from_callable.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/attribute/default_value/from_clonable.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/attribute/default_value/from_symbol.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/attribute/embedded_value.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/attribute/hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/attribute/lazy_default.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/attribute/nullify_blank.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/attribute/strict.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/attribute_set.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/builder/hook_context.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/class_inclusions.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/class_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/coercer.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/configuration.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/const_missing_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/instance_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/model.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/module_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/support/equalizer.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/support/options.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/support/type_lookup.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/value_object.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/lib/virtus/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/integration/building_module_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/integration/collection_member_coercion_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/integration/custom_attributes_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/integration/custom_collection_attributes_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/integration/default_values_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/integration/defining_attributes_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/integration/embedded_value_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/integration/extending_objects_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/integration/hash_attributes_coercion_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/integration/inheritance_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/integration/injectible_coercers_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/integration/mass_assignment_with_accessors_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/integration/overriding_virtus_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/integration/required_attributes_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/integration/struct_as_embedded_value_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/integration/using_modules_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/integration/value_object_with_custom_constructor_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/integration/virtus/instance_level_attributes_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/integration/virtus/value_object_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/shared/constants_helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/shared/freeze_method_behavior.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/shared/idempotent_method_behaviour.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/shared/options_class_method.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/boolean/coerce_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/boolean/value_coerced_predicate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/class_methods/build_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/class_methods/coerce_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/coerce_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/coercible_predicate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/collection/class_methods/build_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/collection/coerce_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/custom_collection_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/defined_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/embedded_value/class_methods/build_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/embedded_value/coerce_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/get_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/hash/class_methods/build_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/hash/coerce_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/lazy_predicate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/rename_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/required_predicate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/set_default_value_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/set_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute/value_coerced_predicate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute_set/append_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute_set/define_reader_method_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute_set/define_writer_method_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute_set/each_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute_set/element_reference_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute_set/element_set_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute_set/merge_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute_set/reset_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attribute_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attributes_reader_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/attributes_writer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/class_methods/finalize_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/class_methods/new_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/config_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/element_reader_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/element_writer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/freeze_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/model_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/module_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/set_default_attributes_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/spec/unit/virtus/value_object_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/virtus-1.0.5/virtus.gemspec
/usr/lib64/ruby/gems/2.3.0/specifications/virtus-1.0.5.gemspec
